### ISSUE TITLE
Get address of sender in message?

### ISSUE THREAD

**Issue by jedahan** [adzialocha/osc-js#28]
if we are using the datagram plugin, is there a way to pass along the sender address of any message we receive in the `.on('/someaddress', callback)`

**Comment by adzialocha** [comment]
So far this functionality does not exist since I wanted to keep the library as simple as possible, but I will mark it as a feature request since it totally makes sense to build it in.

For now you can write your own datagram plugin (https://github.com/adzialocha/osc-js/wiki/Plugin-API), hook it into `osc-js` and extend it with this functionality by passing on the needed information.

**Comment by olange** [comment]
I'd be interested for such an enhancement too and wanted to share our use case. 

We're using a [TouchOSC](https://hexler.net/software/touchosc) controller on iPad/iPhone, with [P5Camera](https://github.com/olange/touchosc-layouts) layout, to control a 3D camera in an app; the app sends feedback from the controller, to update its labels with the new coordinates of the camera.

When we run our web app in different browser windows simultaneously, all the cameras receive the same OSC controlling messages – although they might look at different scenes / different directions initially.

Having the address of the sender would allow each web app to listen to its own controller, and filter out the other messages.
