### ISSUE TITLE
Implement booleans

### ISSUE THREAD

**Issue by s-ol** [adzialocha/osc-js#56]
The boolean type tags are listed in the wiki but don't actually work:

- [`TypedMessage.pack`](https://github.com/adzialocha/osc-js/blob/master/src/message.js#L140) doesn't implement them
- [`TypedMessage.unpack`](https://github.com/adzialocha/osc-js/blob/master/src/message.js#L202) implements them wrongly (will end the message if it encounters a boolean)
- [`typeTag`](https://github.com/adzialocha/osc-js/blob/6cc2c605c4df30318e6bcf227b0aa65164fec17b/src/common/helpers.js#L15-L2) doesn't implement them, meaning `Message.add` can't use them

Also, while in the OSC protocol booleans take no space in the message encoding, I think it would be beneficial to add `true`/`false` values into `TypedMessage.args` at the corresponding position. Otherwise the mapping from `type` to `args` is broken, which means the user has to essentially re-parse the type string just to find the corresponding value.

**Comment by adzialocha** [comment]
Oh, thanks for the note @s-ol, think I've overlooked this one when merging https://github.com/adzialocha/osc-js/pull/48.

Ping @davidgranstrom, maybe you have an idea what is missing?

**Comment by davidgranstrom** [comment]
@s-ol @adzialocha I think that adding corresponding values for the `T,F` (and `I,N`) types in order to keep symmetry between args and typetag makes sense. 

It was a while since I wrote the PR so I would have to take a closer look to see what is actually needed. But I think it is mainly about adding the values in `Message.unpack` when looping over the typetag string and also accept values in the `typeTag` helper function. I don't think `Message.pack` would need to implement this since these types are not part of the binary OSC message data.

**Comment by adzialocha** [comment]
I had a go on an implementation here, please have a look if you have time: https://github.com/adzialocha/osc-js/pull/59

**Comment by davidgranstrom** [comment]
@adzialocha That was fast :) Looks good to me! 👍

**Comment by adzialocha** [comment]
Super, lets release it then!
